version: "3"

services:
  frontend:
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./app:/usr/share/nginx/html
    labels:
      - traefik.frontend.rule=Host:countdown.hmnd.de
      - traefik.docker.network=traefik_net
      - traefik.enable=true
      - traefik.port=80
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true